# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eluxity' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eluxity

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'


  target 'eluxity-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eluxityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eluxity-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eluxity-tvOS

end
